// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR5GUYF8dMT-rwixMFLc2eQ7jN2vS9A_0',
    appId: '1:596697920383:android:d9989f05c029001fff204a',
    messagingSenderId: '596697920383',
    projectId: 'ltcadsmk',
    databaseURL: 'https://ltcadsmk-default-rtdb.firebaseio.com',
    storageBucket: 'ltcadsmk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdVKineRuWNS09mxvq8D1XLb8MjT7Hcqs',
    appId: '1:596697920383:ios:068d9ff57ae19549ff204a',
    messagingSenderId: '596697920383',
    projectId: 'ltcadsmk',
    databaseURL: 'https://ltcadsmk-default-rtdb.firebaseio.com',
    storageBucket: 'ltcadsmk.firebasestorage.app',
    iosClientId: '596697920383-278981abanl9i8eun9mi7bhg96nr8s2l.apps.googleusercontent.com',
    iosBundleId: 'com.ltcgiga.earn.cloudmining.ltcmining.giga',
  );

}